export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DASHBOARD_PAGE = 'DASHBOARD_PAGE';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GETALL_CATEGORY = 'GETALL_CATEGORY';
export const GETUSER_CATEGORY = 'GETUSER_CATEGORY';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GETPRODUCT_BYSELL = 'GETPRODUCT_BYSELL';
export const GETPRODUCT_BYARRIVAL = 'GETPRODUCT_BYARRIVAL';
export const RELATED_PRODUCTS = 'RELATED_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const BUYER_CATEGORY = 'BUYER_CATEGORY';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const TOTAL_ITEM = 'TOTAL_ITEM';
export const GET_ITEM = 'GET_ITEM';










